### ISSUE TITLE
Error while preprocessing

### ISSUE THREAD

**Issue by ajr82** [secrierlab/HistoMIL#1]
Hi, I get an error when trying to pre-process. 

I am running this in Windows 11, Python 3.8

Traceback (most recent call last):
  File "pre_processing.py", line 100, in <module>
    exp.init_cohort()
  File "E:\McGill projects\Lymphoma\Experiment\HistoMIL\..\HistoMIL\EXP\workspace\experiment.py", line 91, in init_cohort
    self.data_cohort.setup_taskcohort(
  File "E:\McGill projects\Lymphoma\Experiment\HistoMIL\DATA\Cohort\data.py", line 92, in setup_taskcohort
    self.task_cohort.build(local_df=self.local_cohort.usable_df(task_concepts))
  File "E:\McGill projects\Lymphoma\Experiment\HistoMIL\DATA\Cohort\basic.py", line 299, in build
    patinet_df = self.sort_patientID(table = source_table,pid_name=self.pid_name,labels_name=self.labels_name)
  File "E:\McGill projects\Lymphoma\Experiment\HistoMIL\DATA\Cohort\basic.py", line 128, in sort_patientID
    data_dict.update({name:table.df[name].values.tolist()})
  File "C:\Users\ajraj_t7g\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\ajraj_t7g\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'lymphoma'

**Comment by RunningStone** [comment]
Hi, It seems that you not define this key "lymphoma" in CohortParas ? could you please specify how you define it in your file? Cause our task not related with "lymphoma" and all of our pre-defined parameters will not include this string as well.
